version: "3.4"

x-common-variables:
  &common-variables
  MYSQL_USER: simple
  MYSQL_PASSWORD: 123456789
  MYSQL_DATABASE: iqraaly
  REACT_APP_SERVER_PORT: 3000

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql

  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always

  server:
    # build can be specified as a string (or as an object) containing a path to the build context
    build: ./server/express
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      DB_HOST: mysql-db
      DB_USER: 'simple'
      DB_NAME: "iqraaly"
      DB_PASSWORD: "123456789"
    ports:
      - 3001:3001
    # volumes are the persistent data connected to each container
    volumes:
      - ./server:/app
    # links is used to make connections between containers
    links:
      - mysql-db
    command: npm start
  client:
    build: ./client
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    # ports for client (front) http://localhost:3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start
